# vLLM Router Release Pipeline
# This pipeline is triggered on version tags (v*) to build and publish releases

env:
  CARGO_INCREMENTAL: "0"
  RUST_BACKTRACE: "1"

steps:
  # ============================================================================
  # Version Consistency Check
  # ============================================================================
  - label: ":mag: Verify Version Tag Matches pyproject.toml"
    key: "version-check"
    command: |
      set -euo pipefail

      # Extract version from git tag (e.g., v0.1.0 -> 0.1.0)
      TAG_VERSION="$${BUILDKITE_TAG#v}"
      echo "Git tag version: $TAG_VERSION"

      # Extract version from pyproject.toml
      PYPROJECT_VERSION=$(grep -E '^version\s*=' pyproject.toml | sed 's/.*=\s*"\(.*\)"/\1/')
      echo "pyproject.toml version: $PYPROJECT_VERSION"

      # Compare versions
      if [ "$TAG_VERSION" != "$PYPROJECT_VERSION" ]; then
        echo "❌ ERROR: Version mismatch!"
        echo "   Git tag version:       $TAG_VERSION"
        echo "   pyproject.toml version: $PYPROJECT_VERSION"
        echo ""
        echo "Please update pyproject.toml to match the git tag before releasing."
        exit 1
      fi

      echo "✅ Version check passed: $TAG_VERSION"
    if: build.tag =~ /^v.*/
    agents:
      queue: "cpu_queue_postmerge"

  - wait

  # ============================================================================
  # Build Release Artifacts
  # ============================================================================
  - label: ":package: Build Release Artifacts"
    key: "build_wheels"
    plugins:
      - docker#v5.11.0:
          image: "rustlang/rust:nightly-bullseye"
          workdir: /workdir
          volumes:
            - ".:/workdir"
          environment:
            - "CARGO_INCREMENTAL=0"
            - "RUST_BACKTRACE=1"
          command:
            - bash
            - -c
            - |
              set -euo pipefail

              # Install system dependencies
              apt-get update && apt-get install -y pkg-config libssl-dev protobuf-compiler python3 python3-pip

              # Build Rust binary for release
              cargo build --release

              # Build Python wheels
              pip3 install -U pip setuptools wheel setuptools-rust build
              python3 -m build
    artifact_paths:
      - "target/release/vllm-router"
      - "dist/*.whl"
      - "dist/*.tar.gz"
    depends_on: "version-check"
    agents:
      queue: "cpu_queue_postmerge"

  - wait

  # ============================================================================
  # Run Release Tests
  # ============================================================================
  - label: ":test_tube: Smoke Test Release Binary"
    command: |
      buildkite-agent artifact download "target/release/vllm-router" .
      chmod +x target/release/vllm-router
      docker run --rm -v "$$PWD:/workdir" -w /workdir rustlang/rust:nightly-bullseye ./target/release/vllm-router --version
      docker run --rm -v "$$PWD:/workdir" -w /workdir rustlang/rust:nightly-bullseye ./target/release/vllm-router --help
    agents:
      queue: "cpu_queue_postmerge"

  - label: ":python: Test Python Wheel"
    command: |
      buildkite-agent artifact download "dist/*.whl" .
      pip install dist/*.whl
      python -c "import vllm_router; print(vllm_router.__version__)"
    agents:
      queue: "cpu_queue_postmerge"

  - wait

  # ============================================================================
  # Publish to PyPI
  # ============================================================================
  - label: ":python: Publish to PyPI"
    key: "publish-pypi"
    plugins:
      - docker#v5.11.0:
          image: "python:3.11-slim"
          workdir: /workdir
          volumes:
            - ".:/workdir"
          environment:
            - "TWINE_USERNAME=__token__"
            - "TWINE_PASSWORD"
          propagate-environment: true
          command:
            - bash
            - -c
            - |
              set -euo pipefail

              pip install twine

              echo "📦 Uploading packages to PyPI..."
              twine upload dist/* --verbose

              echo "✅ Successfully published to PyPI!"
    env:
      TWINE_PASSWORD: "${PYPI_TOKEN}"
    depends_on: "build_wheels"
    if: build.tag =~ /^v.*/
    soft_fail: false
    agents:
      queue: "cpu_queue_postmerge"

  # ============================================================================
  # Create GitHub Release
  # ============================================================================
  - label: ":github: Create GitHub Release"
    command: |
      # Download all artifacts
      buildkite-agent artifact download "target/release/vllm-router" .
      buildkite-agent artifact download "dist/*" .

      # Create GitHub release (requires gh CLI and GITHUB_TOKEN)
      gh release create $${BUILDKITE_TAG} \
        --title "Release $${BUILDKITE_TAG}" \
        --notes "Release $${BUILDKITE_TAG} of vLLM Router" \
        target/release/vllm-router \
        dist/*.whl \
        dist/*.tar.gz
    if: build.tag =~ /^v.*/
    agents:
      queue: "cpu_queue_postmerge"
